quickr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
]

shop/urls.py
from django.urls import path

from shop import views

urlpatterns = [
    path('secure_view', views.secure_view),

    path('login/', views.login, name = 'login'),
    path('logout/', views.logout, name = 'logout'),

    path('', views.Index.as_view(), name = 'index'),

    path('categories/', views.CategoryList.as_view(), name = 'categories'),
    path('category/<str:slug>', views.CategoryDetail.as_view(), name = 'category'),

    path('product/<int:pk>', views.ProductDetail.as_view(), name = 'product'),

    path('product/<int:product_id>/add_review/', views.ReviewCreate.as_view(), name = 'add_review'),
]

shop/models.py
from django.db import models
# from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length = 100)
    slug = models.SlugField(unique = True)

    def __str__ (self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey('Category', on_delete = models.CASCADE)
    name = models.CharField(max_length = 100)
    price = models.FloatField()

    def __str__ (self):
        return self.name

class Review(models.Model):
    product = models.ForeignKey('Product', on_delete = models.CASCADE)
    content = models.TextField()
    author = models.CharField(max_length = 100)

    def __str__ (self):
        return self.author

shop/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget = forms.PasswordInput())

shop/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView
)
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.models import User
from django.utils.decorators import method_decorator

from shop import models, forms

# Create your views here.

@login_required
def secure_view(request):
    return HttpResponse("You are authenticated")

def login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse_lazy('index'))

    if request.method == "GET":
        form = forms.LoginForm()
    elif request.method == "POST":
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username = username, password = password)
            if user:
                auth_login(request, user)
                return HttpResponseRedirect(reverse_lazy('index'))

    context = {
        'form': form
    }
    return render(request, 'shop/login.html', context)

def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse_lazy('index'))

@method_decorator(login_required, name='dispatch')
class Index(TemplateView):
    template_name = 'shop/index.html'

    # @login_required
    # def dispatch(self, *args, **kwargs):
    #     return super().dispatch(self, *args, **kwargs)

class CategoryList(ListView):
    model = models.Category
    # template_name = ''
    # context_object_name = ''

# def category_list(request):
#     categories = models.Category.objects.all()
#     context = {
#         "object_list": categories
#     }
#     return render(request, 'shop/category_list.html', context)

class CategoryDetail(DetailView):
    model = models.Category

# def category_detail(request, slug):
#     category = models.Category.object.get(slug = slug)

#     context = {
#         "object": category,
#     }
#     return render(request, 'shop/category_detail.html', context)

class ProductDetail(DetailView):
    model = models.Product

class ReviewCreate(CreateView):
    model = models.Review
    fields = ('content', 'author')

    def form_valid(self, form):
        product = models.Product.objects.get(id = self.kwargs['product_id'])
        obj = form.save(commit = False) # create object in memory
        obj.product = product # adding missing data
        obj.save() # hitting the db

        success_url = reverse_lazy('product', kwargs = {"pk":product.id})

        return HttpResponseRedirect(success_url)

# def add_review(request, product_id):
#     if request.method == "GET":
#         form = ReviewForm()
#     elif request.method == "POST":
#         form = ReviewForm(request.POST)
#         if form.is_valid():
#             product = models.Product.objects.get(id = product_id)
#             # obj = models.Review.objects.create(
#             #     product = product,
#             #     content = form.cleaned_data['content'],
#             #     author = form.cleaned_data['author']
#             # )

#             # obj = models.Review(
#             #     content = form.cleaned_data['content'],
#             #     author = form.cleaned_data['author']
#             # )
#             # obj.product = product
#             # obj.save()

#             obj = form.save(commit = False)
#             obj.product = product
#             obj.save()

#     context = {
#         'form': form
#     }
#     return render(request, 'shop/review_form.html', context)

templates/shop/category_detail.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Page Title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
        <script src="main.js"></script>
    </head>
    <body>
        <h1>{{ object.name }}</h1>

        <h3>Products</h3>

        <ul>
            {% for product in object.product_set.all %}
                <li>
                    <a href="{% url 'product' pk=product.pk %}">{{ product }}</a>
                </li>
            {% endfor %}
        </ul>
    </body>
</html>

templates/shop/category_list.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Page Title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
        <script src="main.js"></script>
    </head>
    <body>
        
        <h1>Categories</h1>

        <ul>
            {% for category in object_list %}
                <li>
                    <a href="{% url 'category' slug=category.slug %}">{{ category }}</a>
                </li>
            {% endfor %}
        </ul>

    </body>
</html>

templates/shop/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Page Title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
        <script src="main.js"></script>
    </head>
    <body>
        <h1>Quickr Application</h1>

        <h3>Navigation</h3>
        <ul>
            <li>
                <a href="{% url 'categories' %}">Categories</a>
            </li>
            <li></li>
            <li></li>
        </ul>
    </body>
</html>

templates/shop/login.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Page Title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
        <script src="main.js"></script>
    </head>
    <body>
       <form action="" method="post">
           {% csrf_token %}

            {{form}}

           <button type="submit">Login</button>
       </form> 
    </body>
</html>

templates/shop/product_detail.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Page Title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
        <script src="main.js"></script>
    </head>
    <body>
        <h1>{{ object.name }}</h1>
        <h3>Rs. {{ object.price }}</h3>

        <h3>Reviews</h3>

        <ul>
            {% for review in object.review_set.all %}
                <li>{{ review.content }} - {{ review.author }}</li>
            {% endfor %}
        </ul>

        <a href="{% url 'add_review' product_id=object.id %}">Add Review</a>
    </body>
</html>

templates/shop/review_form.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Page Title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
        <script src="main.js"></script>
    </head>
    <body>
        <h1>Add Review</h1>

        <form action="" method="post">
            {% csrf_token %}

            {{ form }}

            <button type="submit">Submit</button>
        </form>
    </body>
</html>